version: '3'
services:

  dominant: # Keep in sync with $(SERVICE)
    image: $DEV_IMAGE_TAG
    build:
      dockerfile: Dockerfile.dev
      context: .
      args:
        ERLANG_VERSION: $ERLANG_VERSION
        THRIFT_VERSION: $THRIFT_VERSION
    volumes:
      - .:$PWD
    working_dir: $PWD
    depends_on:
      - machinegun
    ports:
      - "8022"
    command: /sbin/init

  machinegun:
    image: docker.io/rbkmoney/machinegun:c05a8c18cd4f7966d70b6ad84cac9429cdfe37ae
    ports:
      - "8022"
    command: /opt/machinegun/bin/machinegun foreground
    volumes:
      - ./test/machinegun/config.yaml:/opt/machinegun/etc/config.yaml
      - ./test/machinegun/cookie:/opt/machinegun/etc/cookie
