name: Build / lint / typecheck / test
on:
  pull_request:
    branches: ['*']

jobs:
  build-check-test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      # https://docs.github.com/en/actions/learn-github-actions/workflow-commands-for-github-actions#setting-an-environment-variable
      - name: Update environment variables
        run: grep -v '^#' .env >> $GITHUB_ENV
        
      - name: Restore PLT cache
        uses: actions/cache@v2
        with:
          key: |
            dialyzer-plt-${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ github.sha }}
          restore-keys: |
            dialyzer-plt-${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-
            dialyzer-plt-${{ runner.os }}-
          path: |
            _build/*/rebar3_*_plt

      - run: make wc-compile
      - run: make wc-xref
      - run: make wc-dialyze
      - run: make wdeps-test
      - run: make wc-lint
